# Generated by Django 4.0.4 on 2022-04-19 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesplayweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(5.1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(12)]),
        ),
    ]
