# Generated by Django 4.0.3 on 2022-04-04 16:52

import django.core.validators
from django.db import migrations, models
import online_music.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), online_music.validators.validators.only_letters_numbers_underscore_validator]),
        ),
    ]
