FIRST_NAME_MAX_LEN = 15
FIRST_NAME_MIN_LEN = 2

LAST_NAME_MAX_LEN = 15
LAST_NAME_MIN_LEN = 2

BUDGET_DEFAULT_VALUE = 0
BUDGET_MIN_VALUE = 0

IMAGE_MAX_SIZE_IN_MB = 5
IMAGE_UPLOAD_TO_DIR = 'profiles/'

VALIDATE_ONLY_LETTERS_EXCEPTION_MESSAGE = "Ensure this value contains only letters."
MB = 1048576    # (1024 * 1024)

TITLE_MAX_LEN = 30