# Generated by Django 4.0.2 on 2022-03-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0003_alter_pet_user_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='user_profile',
        ),
    ]
