# Generated by Django 4.0.2 on 2022-03-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0005_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
    ]
